// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKRMdQTwS3Wx9FuaRWruBxQBk0naQvgLY',
    appId: '1:419268019281:web:fdbfa4df5bd8a922fd6470',
    messagingSenderId: '419268019281',
    projectId: 'chat-app-d14d9',
    authDomain: 'chat-app-d14d9.firebaseapp.com',
    storageBucket: 'chat-app-d14d9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAlwrLE8-jAJgcVmWGCcSCIHSg68wCcG8',
    appId: '1:419268019281:android:7fb511ed18f141a9fd6470',
    messagingSenderId: '419268019281',
    projectId: 'chat-app-d14d9',
    storageBucket: 'chat-app-d14d9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1Gu1EBRkC7_4TjWRW_WYE2pL-Zxyt1VA',
    appId: '1:419268019281:ios:e2d33027fe2c0831fd6470',
    messagingSenderId: '419268019281',
    projectId: 'chat-app-d14d9',
    storageBucket: 'chat-app-d14d9.firebasestorage.app',
    iosBundleId: 'com.example.messengerAppCubit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1Gu1EBRkC7_4TjWRW_WYE2pL-Zxyt1VA',
    appId: '1:419268019281:ios:e2d33027fe2c0831fd6470',
    messagingSenderId: '419268019281',
    projectId: 'chat-app-d14d9',
    storageBucket: 'chat-app-d14d9.firebasestorage.app',
    iosBundleId: 'com.example.messengerAppCubit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKRMdQTwS3Wx9FuaRWruBxQBk0naQvgLY',
    appId: '1:419268019281:web:3e8490ddefc07f44fd6470',
    messagingSenderId: '419268019281',
    projectId: 'chat-app-d14d9',
    authDomain: 'chat-app-d14d9.firebaseapp.com',
    storageBucket: 'chat-app-d14d9.firebasestorage.app',
  );
}
